######################################## 必须修改的的配置 ########################################

# 指定到游戏根目录
'game_path': ''

# 翻译工程文件保存位置，需要保证这个文件夹是已经建好的
# 从旧的翻译工程加载时，这个也是翻译工程的所在路径
'save_path': ''

# 要翻译的xlsx文件保存位置，需要保证这个文件夹是已经建好的
'data_path': ''

# 翻译后的xlsx文件路径,如果不注入游戏，可以先不改
# 游戏版本更新时，此为旧版翻译文件的路径
'translation_path': ''

# 导出注入翻译后的data文件存放位置
'output_path': ''

# 是否为日文游戏，1，是；0，否。非日文游戏必须改为0，否则提取不到文本
'ja': 1

######################################## 推荐修改的配置 ########################################

# 水印，如果设置了，会自动添加到游戏标题上。不设置的话，请改为数字0
'mark': 0

# 提取名字时，会自动反选搜索地址，排除地址中包含以下内容的数据，
# *代表按*拆分文本，会搜索不同时含拆分后的所有文本的数据。如'vent.s*name'代表搜索地址中不同时包含'vents'和'name'的数据
# 默认设置排除了事件名和敌人编队名。道具名为'Items.*name'，技能名为'Skills.*name','States.*name'为状态名，以此类推，对应名字一般包含在对应文件内
'NameWithout': ['vents.*name', 'Troops.*name', 'Skills.*name', 'Items.*name', 'States.*name']

# 自动换行时，每行的字数。不使用时设为0，推荐先不使用，需要的时候再按情况设置后重新注入
'line_length': 40

# 格式为‘特殊文本对应的code’:{‘特殊文本中一定有的文本,如果不限定文本，就用”空“字代替’:'提取对应的正则表达式，用中文句号替换英文单引号'}
'sptext': {
  '355':{'addText':'[^a-zA-z0-9(),。]+'},
  '655':{'空':'[^a-zA-z0-9(),。]+'},
  '356':{'addLog':'[^a-zA-z0-9(),。]+'}
}


######################################## 不推荐修改的配置 ########################################

# 读取文本时，只会读取code是以下内容的文本，-1代表没有code，可以自行添加，但不推荐删减
# 357通用性存疑
'ReadCode': ['-1', '401','405', '101', '102','105','320',"324", '357']

# 如果有连续的这些code，这些文本会被合在一起，就像t++那样
'sumcode' : ['401', '405']

# note中，<:之间的字符串长度占整个字符串长度的比例不足这个数时，全部应用原文，否则只有<:之间的字符串应用原文
# 越小，文本需要的长度就越长。过大会出现note类bug，过小会导致一些比较短的图鉴行漏翻
'note_percent': 0.2


# 地址黑名单，文本地址中包含以下内容的，不会被翻译。默认配置对应的是t++中自动标红标蓝，和事件名，敌人编队名，可以自行添加，但不推荐删减
# 在翻译ACT游戏时，建议把'note'也加入黑名单地址，否则大概率无法攻击或攻击没有效果
'BlackDir': ['vents.*name', 'Troops.*name', 'System.*switches', 'System.*variables', 'SrcEventIdOrName']

# 黑名单code，文本code为以下内容时，不会翻译。默认配置对应的是t++中自动标红标蓝的文本，可以自行添加，但不推荐删减
'BlackCode': []

# 黑名单文件，不会读取其中的内容。默认配置为一般来说不需要翻译的文件
'BlackFiles': ['Animations.json','MapInfos.json','Tilesets.json']

# 处理文件名时，只会处理原文完全等于文件名，或以下分隔符内的文本包含文件名的情况
'codewithnames': [["[","]"],["\"","\""],["<",">"]]

